#!/usr/bin/env bash
# Phase 3.0 — After `amplify push --env prod` completes, discover the new resource
# names in Arthur's account and write them to migration/.env.target so subsequent
# scripts can pick them up automatically.

set -euo pipefail
source "$(dirname "$0")/00-config.sh"

require_profile "$TARGET_PROFILE"

# Try to read the new GraphQL API ID from amplify-meta.json (which now has the prod env).
# Falls back to listing AppSync APIs in the target account.
META_FILE="$MIGRATION_ROOT/../amplify/backend/amplify-meta.json"

if [[ -f "$META_FILE" ]]; then
  TARGET_API_ID=$(jq -r '.api | to_entries[0].value.output.GraphQLAPIIdOutput // empty' "$META_FILE")
fi

if [[ -z "${TARGET_API_ID:-}" ]]; then
  log "amplify-meta.json didn't have a GraphQL API ID; falling back to AppSync list."
  TARGET_API_ID=$(aws appsync list-graphql-apis \
    --profile "$TARGET_PROFILE" --region "$TARGET_REGION" \
    --query "graphqlApis[?contains(name, 'oathsummonstracker')].apiId | [0]" \
    --output text)
fi

if [[ -z "$TARGET_API_ID" || "$TARGET_API_ID" == "None" ]]; then
  err "Could not determine target GraphQL API ID. Has 'amplify push --env prod' run?"
  exit 1
fi

log "Target GraphQL API ID: $TARGET_API_ID"

# Discover Cognito pool, identity pool, S3 bucket, Lambda functions.
TARGET_USER_POOL_ID=$(aws cognito-idp list-user-pools --max-results 50 \
  --profile "$TARGET_PROFILE" --region "$TARGET_REGION" \
  --query "UserPools[?contains(Name, 'oathsummonstracker')].Id | [0]" \
  --output text)

TARGET_USER_POOL_CLIENT_ID=$(aws cognito-idp list-user-pool-clients \
  --user-pool-id "$TARGET_USER_POOL_ID" \
  --profile "$TARGET_PROFILE" --region "$TARGET_REGION" \
  --query "UserPoolClients[?contains(ClientName, 'web') || contains(ClientName, 'Web')].ClientId | [0]" \
  --output text)
# Fallback if naming differs
if [[ -z "$TARGET_USER_POOL_CLIENT_ID" || "$TARGET_USER_POOL_CLIENT_ID" == "None" ]]; then
  TARGET_USER_POOL_CLIENT_ID=$(aws cognito-idp list-user-pool-clients \
    --user-pool-id "$TARGET_USER_POOL_ID" \
    --profile "$TARGET_PROFILE" --region "$TARGET_REGION" \
    --query "UserPoolClients[0].ClientId" --output text)
fi

TARGET_IDENTITY_POOL_ID=$(aws cognito-identity list-identity-pools --max-results 50 \
  --profile "$TARGET_PROFILE" --region "$TARGET_REGION" \
  --query "IdentityPools[?contains(IdentityPoolName, 'oathsummonstracker')].IdentityPoolId | [0]" \
  --output text)

TARGET_S3_BUCKET=$(aws s3api list-buckets \
  --profile "$TARGET_PROFILE" \
  --query "Buckets[?contains(Name, 'oath-evidence-files-${TARGET_ENV_NAME}')].Name | [0]" \
  --output text)
if [[ -z "$TARGET_S3_BUCKET" || "$TARGET_S3_BUCKET" == "None" ]]; then
  TARGET_S3_BUCKET="oath-evidence-files-${TARGET_ENV_NAME}"
fi

# Lambdas
TARGET_DAILYSWEEP_FN="dailySweep-${TARGET_ENV_NAME}"
TARGET_DATAEXTRACTOR_FN="dataExtractor-${TARGET_ENV_NAME}"
TARGET_USERMIGRATION_FN="cognitoUserMigration-${TARGET_ENV_NAME}"

# Cron rule (find the new one)
TARGET_CRON_RULE=$(aws events list-rules \
  --profile "$TARGET_PROFILE" --region "$TARGET_REGION" \
  --query "Rules[?contains(Name, 'oathsummonstracker') && contains(Name, 'CloudWatchEvent')].Name | [0]" \
  --output text)

cat > "$MIGRATION_ROOT/.env.target" <<EOF
# Auto-generated by 05a-discover-target-tables.sh — do not commit.
export TARGET_GRAPHQL_API_ID="$TARGET_API_ID"
export TARGET_USER_POOL_ID="$TARGET_USER_POOL_ID"
export TARGET_USER_POOL_CLIENT_ID="$TARGET_USER_POOL_CLIENT_ID"
export TARGET_IDENTITY_POOL_ID="$TARGET_IDENTITY_POOL_ID"
export TARGET_S3_BUCKET="$TARGET_S3_BUCKET"
export TARGET_DAILYSWEEP_FN="$TARGET_DAILYSWEEP_FN"
export TARGET_DATAEXTRACTOR_FN="$TARGET_DATAEXTRACTOR_FN"
export TARGET_USERMIGRATION_FN="$TARGET_USERMIGRATION_FN"
export TARGET_CRON_RULE="$TARGET_CRON_RULE"

export TARGET_TABLE_CLIENT="Client-\${TARGET_GRAPHQL_API_ID}-${TARGET_ENV_NAME}"
export TARGET_TABLE_SUMMONS="Summons-\${TARGET_GRAPHQL_API_ID}-${TARGET_ENV_NAME}"
export TARGET_TABLE_SYNC_STATUS="SyncStatus-\${TARGET_GRAPHQL_API_ID}-${TARGET_ENV_NAME}"
export TARGET_TABLE_INVOICE="Invoice-\${TARGET_GRAPHQL_API_ID}-${TARGET_ENV_NAME}"
export TARGET_TABLE_INVOICE_SUMMONS="InvoiceSummons-\${TARGET_GRAPHQL_API_ID}-${TARGET_ENV_NAME}"

export TARGET_TABLES=(
  "\$TARGET_TABLE_CLIENT"
  "\$TARGET_TABLE_SUMMONS"
  "\$TARGET_TABLE_SYNC_STATUS"
  "\$TARGET_TABLE_INVOICE"
  "\$TARGET_TABLE_INVOICE_SUMMONS"
)
EOF

log "Wrote $MIGRATION_ROOT/.env.target"
log "Summary:"
cat "$MIGRATION_ROOT/.env.target"
